### ISSUE TITLE
EOT font support

### ISSUE THREAD

**Issue by skyrpex** [ericfreese/font-viewer#5]
Is there a reason not to support EOT fonts?

Regards,

**Comment by ericfreese** [comment]
The font-viewer package currently shows every available glyph in the selected font. To get a list of available glyphs, it uses the [freetype2 module](https://github.com/ericfreese/node-freetype2) to parse the font file. The Freetype library doesn't support EOT files, so font-viewer doesn't either.

However, EOT files could be handled differently. We'd just need to find a way to retrieve a list of available characters.

Looking at the [specification](http://www.w3.org/Submission/EOT/#FileFormat), the OpenType/TrueType font data is available at the end of the file, BUT in some files (I have no idea how many), it's compressed with a proprietary algorithm so that we can't decompress it. Files that are compressed have a `TTEMBED_TTCOMPRESSED` flag, so we could try detecting if that flag is set and opening the file if it's not.

So the end result would be that font-viewer could theoretically open uncompressed EOT files but not compressed ones.

Pull requests welcome ;) There's an [eot-parser module](https://github.com/andyjansson/eot-parser) that looks like it would be a decent starting point, but it doesn't currently load the processing flags or the font data.

More info:
- http://graphicdesign.stackexchange.com/questions/16234/are-there-any-free-tools-to-convert-eot-files-to-ttf-otf-or-any-other-font-f
- http://securitylabs.websense.com/content/Blogs/3114.aspx
- http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/docs/formats.txt
- https://lists.gnu.org/archive/html/freetype/2003-04/msg00074.html

**Comment by skyrpex** [comment]
Mind if I close this? I don't have the time to create a merge request...

Feel free to reopen this if you want.
